export declare type Easing = (t: number) => number;
export declare function linear(t: number): number;
export declare function easeInQuad(t: number): number;
export declare function easeOutQuad(t: number): number;
export declare function easeInOutQuad(t: number): number;
export declare function easeInCubic(t: number): number;
export declare function easeOutCubic(t: number): number;
export declare function easeInOutCubic(t: number): number;
export declare function easeInQuart(t: number): number;
export declare function easeOutQuart(t: number): number;
export declare function easeInOutQuart(t: number): number;
export declare function easeInQuint(t: number): number;
export declare function easeOutQuint(t: number): number;
export declare function easeInOutQuint(t: number): number;
